# Generated by Django 4.1.7 on 2023-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="total_like",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["-total_like"], name="images_imag_total_l_e2ea5d_idx"
            ),
        ),
    ]
